/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "media",
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#f0f5ff",
          100: "#e0ebff",
          200: "#c7d9fe",
          300: "#a4c0fd",
          400: "#7a9ff9",
          500: "#5a7ef2",
          600: "#007aff",
          700: "#0063d1",
          800: "#0050aa",
          900: "#003d85",
        },
        apple: {
          // Light mode
          bg: "#f2f2f7",
          card: "#ffffff",
          groupedBg: "#f2f2f7",
          separator: "rgba(60,60,67,0.12)",
          label: "#000000",
          secondaryLabel: "#3c3c43",
          tertiaryLabel: "#8e8e93",
          // Dark mode equivalents (prefixed with d-)
          "d-bg": "#000000",
          "d-card": "#1c1c1e",
          "d-groupedBg": "#000000",
          "d-separator": "rgba(84,84,88,0.65)",
          "d-label": "#ffffff",
          "d-secondaryLabel": "#ebebf5",
          "d-tertiaryLabel": "#ebebf599",
          "d-elevated": "#2c2c2e",
          // System colors (same in both modes)
          red: "#ff3b30",
          orange: "#ff9500",
          yellow: "#ffcc00",
          green: "#34c759",
          teal: "#5ac8fa",
          blue: "#007aff",
          indigo: "#5856d6",
          purple: "#af52de",
          pink: "#ff2d55",
          gray: "#8e8e93",
          gray2: "#aeaeb2",
          gray3: "#c7c7cc",
          gray4: "#d1d1d6",
          gray5: "#e5e5ea",
          gray6: "#f2f2f7",
          // Dark mode grays
          "d-gray": "#8e8e93",
          "d-gray2": "#636366",
          "d-gray3": "#48484a",
          "d-gray4": "#3a3a3c",
          "d-gray5": "#2c2c2e",
          "d-gray6": "#1c1c1e",
        },
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "SF Pro Display",
          "SF Pro Text",
          "Helvetica Neue",
          "Hiragino Sans",
          "Hiragino Kaku Gothic ProN",
          "sans-serif",
        ],
      },
      borderRadius: {
        "apple": "12px",
        "apple-lg": "16px",
        "apple-xl": "20px",
      },
      boxShadow: {
        "apple": "0 0.5px 0 0 rgba(0,0,0,0.05)",
        "apple-card": "0 2px 12px rgba(0,0,0,0.08)",
        "apple-elevated": "0 8px 32px rgba(0,0,0,0.12)",
        "apple-modal": "0 20px 60px rgba(0,0,0,0.3)",
      },
      backdropBlur: {
        "apple": "20px",
      },
    },
  },
  plugins: [],
};
